### ISSUE TITLE
Meta

### ISSUE THREAD

**Issue by olafveerman** [energy-data/africa-grid-explorer#1]
Add correct description + url to:

- meta descriptions on `index.html`
- `package.json`
- `readme.md`

@carderne @Naigege What description do you want to add?

**Comment by carderne** [comment]
@olafveerman 
For `readme.md`, we could use the About text? Will share shortly.
For the other two, what you have should be sufficient I think.

> A visualization of the electricity grid in Sub Saharan Africa.
