### ISSUE TITLE
Dataset updated

### ISSUE THREAD

**Issue by carderne** [energy-data/africa-grid-explorer#4]
@olafveerman 
I have updated the source dataset.
Is it pulled automatically or do you need to do something?

**Comment by carderne** [comment]
Dataset has been updated again, for the last time before the launch.

**Comment by olafveerman** [comment]
Made a change (https://github.com/energy-data/africa-grid-explorer/commit/281b6b54642a7440b6ad6d4b5a19f8b1cf9ad1d6) that will dynamically get the correct tilejson. It assumes that the relevant resource is the first one in the dataset.
